version: '3'

services:
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      external_links:
        - db
      ports:
        - "8080:8080"
#      environment:
#        VIRTUAL_HOST: phpmyadmin.yourdomain.com

networks:
    default:
      external:
        name: webproxy

