version: '3'

services:
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      external_links:
        - db
      environment:
        VIRTUAL_HOST: phpmyadmin.budhi.com.br

networks:
    default:
      external:
        name: webproxy

